// <auto-generated />
using System;
using BlogApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogApp.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20191018032537_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlogApp.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "James",
                            Category = "Sport",
                            DatePosted = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sports article 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Mary",
                            Category = "Food",
                            DatePosted = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Food article 1"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Lu",
                            Category = "Coding",
                            DatePosted = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Coding article 1"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Frank",
                            Category = "Weather",
                            DatePosted = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wheather article 1"
                        },
                        new
                        {
                            Id = 5,
                            Author = "James",
                            Category = "Sport",
                            DatePosted = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sports article 2"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Mary",
                            Category = "Food",
                            DatePosted = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Food article 2"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Lu",
                            Category = "Coding",
                            DatePosted = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Coding article 2"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Frank",
                            Category = "Weather",
                            DatePosted = new DateTime(2019, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wheather article 2"
                        },
                        new
                        {
                            Id = 9,
                            Author = "James",
                            Category = "Sport",
                            DatePosted = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sports article 3"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Mary",
                            Category = "Food",
                            DatePosted = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Food article 3"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Lu",
                            Category = "Coding",
                            DatePosted = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Coding article 3"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Frank",
                            Category = "Weather",
                            DatePosted = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wheather article 3"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Frank",
                            Category = "Sport",
                            DatePosted = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sports article 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
